Copy packaging/debian/DEBIAN/* from agent_py2x_pack branch

diff --git a/packaging/debian/DEBIAN/postinst b/packaging/debian/DEBIAN/postinst
--- a/packaging/debian/DEBIAN/postinst
+++ b/packaging/debian/DEBIAN/postinst
@@ -9,30 +9,50 @@
 PACKAGE="proactive-agent"
 INSTALLDIR="/opt/$PACKAGE"
 PAUSER="proactive"
-PAPASS="h3pneM.s.s6G2" # openssl passwd ActiveE0n
+PAPASS="KyVd.Qs65uwR6"
 PAGROUP="proactivegroup"
 PROACTIVEHOME="$INSTALLDIR/schedworker"
 CONFIGXMLBASE="$INSTALLDIR/config-*.xml"
+CONFIGXMLFULL="$INSTALLDIR/config-fulltime.xml"
+CONFIGXML="$INSTALLDIR/config.xml"
 CREDPATH="$PROACTIVEHOME/config/authentication/rm.cred"
+BUNDLEJREDIR="$INSTALLDIR/jre"
+RT_UNPACKED="$BUNDLEJREDIR/lib/rt.jar"
+RT_PACKED="$RT_UNPACKED.pack.gz"
 
 # User and group management
 \groupadd $PAGROUP
-#\useradd -m -s /bin/bash $PAUSER --password $PAPASS
-\useradd $PAUSER --password $PAPASS
+\useradd -m -s /bin/bash $PAUSER --password $PAPASS
+#\useradd $PAUSER --password $PAPASS
 \usermod -aG $PAGROUP $PAUSER
 \chown -R $PAUSER:$PAGROUP $INSTALLDIR
 # TODO : Check user creation
 
-
-# Java configuration
-JAVAPATH=$(readlink -f `which java`| sed "s:/jre/bin/java::")
-# TODO : Run a java Test
-if [ "$?" = "1" ]
+# Check for bundled jre
+if [ -d $BUNDLEJREDIR ]
 then
-    # TODO : We can wget http://download.oracle.com/otn-pub/java/jdk/6u34-b04/jre-6u34-linux-i586.bin
-    echo "ERROR: Please setup a Java >= 1.6 before installing this package"
-    exit 1
+   # Unpack rt.jar
+   if [ -f $RT_PACKED ]
+   then
+      echo "Unpacking $RT_PACKED ..."
+      cd "$INSTALLDIR/jre/bin" 
+      ./unpack200 -r -J-Xmx1024m $RT_PACKED $RT_UNPACKED
+      cd $(dirname $0)
+   fi
+   JAVAPATH="$INSTALLDIR/jre"
+else
+   # Java configuration
+   JAVAPATH=$(readlink -f `which java`| sed "s:/jre/bin/java::")
+   # TODO : Run a java Test
+   if [ "$?" = "1" ]
+   then
+       # TODO : We can wget http://download.oracle.com/otn-pub/java/jdk/7u25-b15/jdk-7u25-linux-i586.tar.gz
+       echo "ERROR: Please setup a Java >= 1.6 before installing this package"
+       exit 1
+   fi
 fi
+
+echo "Using $JAVAPATH in $CONFIGXMLBASE configuration files ..."
 
 # Set paths in configuration files
 for f in $CONFIGXMLBASE; do
@@ -42,6 +62,11 @@ for f in $CONFIGXMLBASE; do
       -e "s!SET_CREDENTIAL!$CREDPATH!g" $f
 done
 
+echo "Note: Using $CONFIGXMLFULL as default configuration, if changed, please restart the daemon ex: /etc/init.d/$PACKAGE restart"
+\ln -f -s $CONFIGXMLFULL $CONFIGXML
+
 # Service setup
+#cp $INSTALLDIR/$PACKAGE /etc/init.d/
+\chmod 755 /etc/init.d/$PACKAGE 
 \update-rc.d $PACKAGE defaults
 /etc/init.d/$PACKAGE start
